# Generated by Django 5.1.15 on 2026-09-17 03:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('methodology', models.TextField(blank=True)),
                ('expected_results', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='projects.researchproject')),
            ],
            options={
                'ordering': ['project_id'],
                'indexes': [models.Index(fields=['status'], name='proposals_status_idx'), models.Index(fields=['submitted_at'], name='proposals_submitted_at_idx')],
            },
        ),
    ]
