# Generated by Django 5.1.15 on 2026-09-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_list_filter_indexes'),
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['status'], name='proposals_status_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['submitted_at'], name='proposals_submitted_at_idx'),
        ),
    ]
