# Generated by Django 5.1.15 on 2026-09-16 23:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectstatus_resubmitted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='researchproject',
            index=models.Index(fields=['status'], name='projects_status_idx'),
        ),
        migrations.AddIndex(
            model_name='researchproject',
            index=models.Index(fields=['-created_at'], name='projects_created_at_idx'),
        ),
    ]
