# Generated by Django 5.1.15 on 2026-09-15 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.TextField()),
                ('journal', models.CharField(blank=True, max_length=255)),
                ('doi', models.CharField(blank=True, max_length=255)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='projects.researchproject')),
            ],
            options={
                'ordering': ['-publication_date', 'title'],
            },
        ),
    ]
