# Generated by Django 5.1.15 on 2026-09-17 03:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('EXISTING', 'Existing'), ('RESULTING', 'Resulting')], default='EXISTING', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('authors', models.TextField()),
                ('journal', models.CharField(blank=True, max_length=255)),
                ('doi', models.CharField(blank=True, max_length=255)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='projects.researchproject')),
            ],
            options={
                'ordering': ['-publication_date', 'title'],
                'indexes': [models.Index(fields=['-publication_date'], name='publications_pub_date_idx')],
            },
        ),
    ]
