# Generated by Django 5.1.15 on 2026-09-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='kind',
            field=models.CharField(choices=[('EXISTING', 'Existing'), ('RESULTING', 'Resulting')], default='EXISTING', max_length=20),
        ),
    ]
