# Generated by Django 5.1.15 on 2026-09-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_list_filter_indexes'),
        ('publications', '0002_add_kind_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['-publication_date'], name='publications_pub_date_idx'),
        ),
    ]
