# Generated by Django 5.1.15 on 2026-09-16 23:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
        ('projects', '0003_list_filter_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['status'], name='invitations_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['email'], name='invitations_email_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['project', 'status'], name='invitations_project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['-created_at'], name='invitations_created_at_idx'),
        ),
    ]
