# Generated by Django 5.1.15 on 2026-09-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='installation',
            index=models.Index(fields=['status'], name='facilities_instl_status_idx'),
        ),
        migrations.AddIndex(
            model_name='instrument',
            index=models.Index(fields=['installation', 'status'], name='facilities_instr_inst_st_idx'),
        ),
    ]
