/** English UI copy for admin-ui (no i18n yet). */
export const copy = {
  brand: 'ResearchHub Admin',
  dashboard: 'Dashboard',
  logIn: 'Log in',
  logOut: 'Log out',
  email: 'Email',
  password: 'Password',
  close: 'Close',
  cancel: 'Cancel',
  loading: 'Loading…',
  save: 'Save',
  toggleNav: 'Toggle navigation',
  loginTitle: 'Admin sign in',
  loginSubtitle: 'Platform administrators only.',
  loginSubmit: 'Sign in',
  loginFailed: 'Login failed.',
  adminOnly: 'This app is for platform administrators only.',
  requestFailed: 'Request failed',
  loadFailed: 'Could not load data.',
  dashboardSubtitle: 'Platform overview and proposal review.',
  totalProjects: 'Total projects',
  pendingProposals: 'Pending proposals',
  scheduledExperiments: 'Scheduled experiments',
  completedProjects: 'Completed projects',
  researchers: 'Researchers',
  pendingInvitations: 'Pending invitations',
  publications: 'Publications',
  reviewTitle: 'Pending review',
  reviewEmpty: 'No proposals waiting for review.',
  approve: 'Approve',
  reject: 'Reject',
  approving: 'Approving…',
  rejecting: 'Rejecting…',
  approveTitle: 'Approve proposal',
  rejectTitle: 'Reject proposal',
  approveMessage: 'Approve this proposal and move the project to APPROVED?',
  rejectMessage: 'Reject this proposal and return the project to DRAFT?',
  reviewComment: 'Review comment (optional)',
  project: 'Project',
  methodology: 'Methodology',
  expectedResults: 'Expected results',
  submittedAt: 'Submitted',
  emailRequired: 'Email is required.',
  emailInvalid: 'Enter a valid email address.',
  passwordRequired: 'Password is required.',
  passwordMin: 'Password must be at least 8 characters.',
} as const
