/** English UI copy for admin-ui (no i18n yet). */
export const copy = {
  brand: 'ResearchHub Admin',
  dashboard: 'Dashboard',
  users: 'Researchers',
  admins: 'Admins',
  projects: 'Projects',
  proposals: 'Proposals',
  experiments: 'Experiments',
  installations: 'Installations',
  instruments: 'Instruments',
  publications: 'Publications',
  invitations: 'Invitations',
  navPeople: 'People',
  navResearch: 'Research',
  navFacilities: 'Facilities',
  navContent: 'Content',
  logIn: 'Log in',
  logOut: 'Log out',
  accountMenu: 'Account menu',
  email: 'Email',
  password: 'Password',
  showPassword: 'Show password',
  hidePassword: 'Hide password',
  close: 'Close',
  cancel: 'Cancel',
  edit: 'Edit',
  loading: 'Loading…',
  save: 'Save',
  toggleNav: 'Toggle navigation',
  loginTitle: 'Admin sign in',
  loginSubtitle: 'Platform administrators only.',
  loginSubmit: 'Sign in',
  loginFailed: 'Login failed.',
  adminOnly: 'This app is for platform administrators only.',
  requestFailed: 'Request failed',
  loadFailed: 'Could not load data.',
  dashboardSubtitle: 'Platform overview and proposal review.',
  totalProjects: 'Total projects',
  pendingProposals: 'Pending proposals',
  scheduledExperiments: 'Scheduled experiments',
  completedProjects: 'Completed projects',
  researchers: 'Researchers',
  pendingInvitations: 'Pending invitations',
  reviewTitle: 'Pending review',
  reviewEmpty: 'No proposals waiting for review.',
  reviewAll: 'Open proposals',
  viewAll: 'View all',
  approve: 'Approve',
  reject: 'Reject',
  approving: 'Approving…',
  rejecting: 'Rejecting…',
  approveTitle: 'Approve proposal',
  rejectTitle: 'Reject proposal',
  approveMessage: 'Approve this proposal and move the project to APPROVED?',
  rejectMessage:
    'Reject this proposal? The researcher can revise and resubmit.',
  reviewComment: 'Review comment (optional)',
  project: 'Project',
  methodology: 'Methodology',
  expectedResults: 'Expected results',
  submittedAt: 'Submitted',
  reviewedAt: 'Reviewed',
  emailRequired: 'Email is required.',
  emailInvalid: 'Enter a valid email address.',
  passwordRequired: 'Password is required.',
  passwordMin: 'Password must be at least 8 characters.',
  passwordConfirm: 'Confirm password',
  passwordMismatch: 'Passwords do not match.',
  username: 'Username',
  usernameOptional: 'Username (optional)',
  usernameRequired: 'Username is required.',
  firstName: 'First name',
  lastName: 'Last name',
  account: 'Account',
  accountTitle: 'Account',
  accountSubtitle:
    'Update your profile and password. Email cannot be changed.',
  profileSection: 'Profile',
  passwordSection: 'Password',
  emailHint: 'Email is used to sign in and cannot be changed.',
  saveProfile: 'Save profile',
  saving: 'Saving…',
  currentPassword: 'Current password',
  newPassword: 'New password',
  confirmPassword: 'Confirm new password',
  changePassword: 'Change password',
  changingPassword: 'Changing…',
  profileSaved: 'Profile updated.',
  passwordChanged: 'Password changed.',
  role: 'Role',
  active: 'Active',
  inactive: 'Inactive',
  dateJoined: 'Joined',
  setActive: 'Status',
  activate: 'Activate',
  deactivate: 'Deactivate',
  createAdmin: 'Create admin',
  createAdminTitle: 'Create admin account',
  createAdminSubmit: 'Create admin',
  creatingAdmin: 'Creating…',
  createAdminSuccess:
    'Admin created. Login credentials were emailed to them.',
  createAdminHint:
    'A temporary password will be generated and sent to their email. They should change it on their account page.',
  saved: 'Saved.',
  deleted: 'Deleted.',
  userActivated: 'Account activated.',
  userDeactivated: 'Account deactivated.',
  proposalApproved: 'Proposal approved.',
  proposalRejected: 'Proposal rejected.',
  inviteCancelled: 'Invitation cancelled.',
  projectDeleted: 'Project permanently deleted.',
  usersEmpty: 'No researchers found.',
  usersSubtitle: 'Researcher accounts only. Activate or deactivate as needed.',
  viewUserProjects: 'View projects',
  adminsEmpty: 'No admin accounts found.',
  adminsSubtitle:
    'Platform admins and super admins. Only you can create new admin accounts here.',
  projectsEmpty: 'No projects found.',
  proposalsEmpty: 'No proposals match.',
  experimentsEmpty: 'No experiments found.',
  installationsEmpty: 'No installations found.',
  installationsSubtitle: 'Scientific facilities researchers can select for experiments.',
  instrumentsEmpty: 'No instruments found.',
  instrumentsSubtitle: 'Devices available inside installations.',
  createInstallation: 'Add installation',
  editInstallation: 'Edit installation',
  createInstrument: 'Add instrument',
  editInstrument: 'Edit instrument',
  location: 'Location',
  technique: 'Technique',
  code: 'Code',
  name: 'Name',
  installation: 'Installation',
  available: 'Available',
  unavailable: 'Unavailable',
  delete: 'Delete',
  deleteInstallationTitle: 'Delete installation',
  deleteInstallationMessage:
    'Delete this installation? It must have no instruments.',
  deleteInstrumentTitle: 'Delete instrument',
  deleteInstrumentMessage:
    'Delete this instrument? It must not be used by experiments.',
  publicationsEmpty: 'No publications found.',
  invitationsEmpty: 'No invitations found.',
  owner: 'Owner',
  status: 'Status',
  createdAt: 'Created',
  updatedAt: 'Updated',
  description: 'Description',
  scientificObjective: 'Scientific objective',
  members: 'Members',
  proposalStatus: 'Proposal status',
  experimentCount: 'Experiments',
  publicationCount: 'Publications',
  pendingInviteCount: 'Pending invites',
  sectionProposal: 'Proposal',
  sectionTeam: 'Team',
  sectionExperiments: 'Experiments',
  sectionPublications: 'Publications',
  sectionInvitations: 'Invitations',
  emptyProposal: 'No proposal for this project.',
  emptyMembers: 'No team members.',
  emptyExperiments: 'No experiments.',
  emptyPublicationsSection: 'No publications.',
  emptyInvitationsSection: 'No invitations.',
  publicationDetailTitle: 'Publication',
  backToProjects: 'Back to projects',
  deleteProject: 'Delete project',
  deleteProjectTitle: 'Delete project',
  deleteProjectMessage:
    'Permanently delete this project and all related data? This cannot be undone.',
  deleting: 'Deleting…',
  none: '—',
  instrument: 'Instrument',
  scheduledDate: 'Scheduled',
  notes: 'Notes',
  title: 'Title',
  authors: 'Authors',
  journal: 'Journal',
  doi: 'DOI',
  publicationDate: 'Published',
  url: 'URL',
  invitedBy: 'Invited by',
  expiresAt: 'Expires',
  cancelInvite: 'Revoke',
  cancelInviteTitle: 'Revoke invitation',
  cancelInviteMessage: 'Revoke this pending invitation? The invite link will stop working.',
  cancelInviteConfirm: 'Revoke invitation',
  cancelInviteKeep: 'Keep invitation',
  cancelling: 'Revoking…',
  filterAll: 'All',
  filterDraft: 'Draft',
  filterPending: 'Pending',
  filterApproved: 'Approved',
  filterRejected: 'Rejected',
  filterActive: 'Active',
  filterInactive: 'Inactive',
  searchPlaceholder: 'Search…',
  searchProjects: 'Search title or owner email',
  searchUsers: 'Search email or username',
  searchInvitations: 'Search invite email',
  searchPublications: 'Search title, authors, DOI…',
  searchInstallations: 'Search name or location',
  searchInstruments: 'Search code, name, technique',
  searchProposals: 'Search project title',
  kindExisting: 'Existing',
  kindResulting: 'Resulting',
  kind: 'Kind',
  resubmitted: 'Resubmitted',
  previousReviewComment: 'Previous review comment',
  actions: 'Actions',
} as const
