/** English UI copy for admin-ui (no i18n yet). */
export const copy = {
  brand: 'ResearchHub Admin',
  dashboard: 'Dashboard',
  users: 'Users',
  projects: 'Projects',
  proposals: 'Proposals',
  experiments: 'Experiments',
  publications: 'Publications',
  invitations: 'Invitations',
  logIn: 'Log in',
  logOut: 'Log out',
  email: 'Email',
  password: 'Password',
  close: 'Close',
  cancel: 'Cancel',
  loading: 'Loading…',
  save: 'Save',
  toggleNav: 'Toggle navigation',
  loginTitle: 'Admin sign in',
  loginSubtitle: 'Platform administrators only.',
  loginSubmit: 'Sign in',
  loginFailed: 'Login failed.',
  adminOnly: 'This app is for platform administrators only.',
  requestFailed: 'Request failed',
  loadFailed: 'Could not load data.',
  dashboardSubtitle: 'Platform overview and proposal review.',
  totalProjects: 'Total projects',
  pendingProposals: 'Pending proposals',
  scheduledExperiments: 'Scheduled experiments',
  completedProjects: 'Completed projects',
  researchers: 'Researchers',
  pendingInvitations: 'Pending invitations',
  reviewTitle: 'Pending review',
  reviewEmpty: 'No proposals waiting for review.',
  reviewAll: 'Open proposals',
  viewAll: 'View all',
  approve: 'Approve',
  reject: 'Reject',
  approving: 'Approving…',
  rejecting: 'Rejecting…',
  approveTitle: 'Approve proposal',
  rejectTitle: 'Reject proposal',
  approveMessage: 'Approve this proposal and move the project to APPROVED?',
  rejectMessage: 'Reject this proposal and return the project to DRAFT?',
  reviewComment: 'Review comment (optional)',
  project: 'Project',
  methodology: 'Methodology',
  expectedResults: 'Expected results',
  submittedAt: 'Submitted',
  reviewedAt: 'Reviewed',
  emailRequired: 'Email is required.',
  emailInvalid: 'Enter a valid email address.',
  passwordRequired: 'Password is required.',
  passwordMin: 'Password must be at least 8 characters.',
  passwordConfirm: 'Confirm password',
  passwordMismatch: 'Passwords do not match.',
  username: 'Username',
  usernameOptional: 'Username (optional)',
  role: 'Role',
  active: 'Active',
  inactive: 'Inactive',
  dateJoined: 'Joined',
  setActive: 'Status',
  activate: 'Activate',
  deactivate: 'Deactivate',
  createAdmin: 'Create admin',
  createAdminTitle: 'Create admin account',
  createAdminSubmit: 'Create admin',
  creatingAdmin: 'Creating…',
  createAdminSuccess: 'Admin account created.',
  usersEmpty: 'No users found.',
  usersSubtitle:
    'Researchers register themselves. Create new admins here — do not promote researchers.',
  projectsEmpty: 'No projects found.',
  proposalsEmpty: 'No proposals match.',
  experimentsEmpty: 'No experiments found.',
  publicationsEmpty: 'No publications found.',
  invitationsEmpty: 'No invitations found.',
  owner: 'Owner',
  status: 'Status',
  createdAt: 'Created',
  updatedAt: 'Updated',
  description: 'Description',
  scientificObjective: 'Scientific objective',
  members: 'Members',
  proposalStatus: 'Proposal status',
  experimentCount: 'Experiments',
  publicationCount: 'Publications',
  pendingInviteCount: 'Pending invites',
  backToProjects: 'Back to projects',
  deleteProject: 'Delete project',
  deleteProjectTitle: 'Delete project',
  deleteProjectMessage:
    'Permanently delete this project and all related data? This cannot be undone.',
  deleting: 'Deleting…',
  none: '—',
  instrument: 'Instrument',
  scheduledDate: 'Scheduled',
  notes: 'Notes',
  title: 'Title',
  authors: 'Authors',
  journal: 'Journal',
  doi: 'DOI',
  publicationDate: 'Published',
  url: 'URL',
  invitedBy: 'Invited by',
  expiresAt: 'Expires',
  cancelInvite: 'Cancel',
  cancelInviteTitle: 'Cancel invitation',
  cancelInviteMessage: 'Cancel this pending invitation?',
  cancelling: 'Cancelling…',
  filterAll: 'All',
  filterPending: 'Pending',
  filterApproved: 'Approved',
  filterRejected: 'Rejected',
  actions: 'Actions',
} as const
