# Generated by Django 5.1.15 on 2026-09-16 18:41

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super admin'), ('ADMIN', 'Admin'), ('RESEARCHER', 'Researcher')], default='RESEARCHER', max_length=20),
        ),
    ]
