# Generated by Django 5.1.15 on 2026-09-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_add_super_admin_role'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_user_role_idx'),
        ),
    ]
